"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "../components/sideBar";
import { routers_menu } from "../utils/routers";
import Footer from "../components/footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "GeoVisor",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children}) {
  const pathname = usePathname();
  console.log(pathname);
  return (
    <html lang="es">
      <body className={inter.className}>
        <SideBar navLinks={routers_menu} />
        <main className="bg-white mt-16">{children}</main>
        {!pathname.includes("proyectos/")?<Footer />:<></>}
      </body>
    </html>
  );
}
