import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import SideBar from '@riuc/app/components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
        <div className="fixed left-0 top-0 flex w-full justify-left p-10 border-b border-gray-350 bg-gradient-to-b from-zinc-200 pb-6 pt-3 bg-black">
          &nbsp;
          <div className="font-mono font-bold">
          
          <a
            className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
            href="https://ciitt.ucacue.edu.ec/"
            target="_blank"
            rel="noopener noreferrer"
          >
            {' '}
            <Image
              src="/img/ciitt-logo.png"
              alt="CIITT Logo"
              className="dark:invert"
              width={300}
              height={30}
              priority
            />
          </a>
          </div>
          <SideBar />
        </div>
      </div>
        {children}</body>
    </html>
  )
}
