import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@riuc/components/SideBar";
import {routers_menu} from '@utils/routers';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GeoVisor",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <SideBar navLinks={routers_menu} />
       <main className=" min-h-screen flex-col items-center justify-between p-20">
       {children}
       </main>
      </body>
    </html>
  );
}
