export const lista_noticias = [
    {
      Image: "/img/violmuj2024.png",
      id: 1,
      name: "Femicidios y la violencia de Género hacia la Mujer en el Ecuador 2024",
      date: "2024-11-28",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La mujer ecuaroriana ha sido...",
      },
    {
      Image: "/img/migracion2023.png",
      id: 2,
      name: "Migración y Repercusiones en el Ecuador",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 3,
      name: "Observatorio Fenómenos Socioeconómicos",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 4,
      name: "Desarrollo Social",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 5,
      name: "Salud Pública",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 6,
      name: "Comportamiento Urbano",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 7,
      name: "Observatorio Ambiental",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 8,
      name: "Observatorio Natural",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
    {
      Image: "/img/migracion2023.png",
      id: 9,
      name: "Observatorio Innovación Educativa",
      date: "2024-12-06",
      author: "Dr. Maria Emilia de Tinto PhD",
      description: "La migración ....",
    },
      
    ];
    