export const lista_videos = [
    {
      Image: "/img/v-observatorio-socioeconomico.png",
      id: 1,
      to: "/videos/n1",
      name: "Fenómenos Socioeconómicos",
      description: "El observatorio de fenómenos socioeconómicos tiene interés en comprender el comportamiento de los individuos con su entorno en sus distintas dimensiones en ámbito social y económico.",
      date: "Lic. María Emilia Molina de Tinto",
    },
    {
      Image: "/img/v-observatorio-desarrollo-social.png",
      id: 1,
      to: "/videos/n2",
      name: "Desarrollo Social",
      description: "Basados en la Organización Mundial de la Salud (OMS) que define los determinantes sociales de la salud como «las circunstancias en que las personas nacen, crecen, trabajan, viven y envejecen», así como el conjunto de condiciones que pueden modificar el modo de vida de la población (OMS, 2015).",
      date: "Ing. Aura del Cisne Guerrero Luzuriaga & Pisc. Elizabeth León MSc",
    },
    {
      Image: "/img/v-observatorio-salud-publica.png",
      id: 1,
      to: "/videos/n3",
      name: "Salud Pública",
      description: "La salud pública es un conjunto de acciones organizadas por los actores del sistema de salud, con la finalidad de prevenir las enfermedades y también de dar solución a las patologías en los tres niveles de organización del sistema.",
      date: "2Od. Ebingen Villavicencio & Od. Ana Cristina Vásquez ",
    },
    {
        Image: "/img/v-observatorio-urbano.png",
        id: 1,
        to: "/videos/n4",
        name: "Comportamiento Urbano",
        description: "El observatorio comportamiento urbano hace una mirada al comportamiento en el uso de los espacios públicos y en las políticas públicas para uso de los mismos.",
        date: "Arq. Christian Hernán Contreras Escandón",
    },
    {
        Image: "/img/v-observatorio-ambiental.png",
        id: 1,
        to: "/videos/n5",
        name: "Observatorio Ambiental",
        description: "El seguimiento de variables que afectan el medio ambiente constituye el objetivo del observatorio ambiental con el fin de prevenir, reducir y restaurar los daños.",
        date: "Ing. Sandra Cobos Mora",
    },
    {
        Image: "/img/v-observatorio-natural.png",
        id: 1,
        to: "/videos/n6",
        name: "Observatorio Natural",
        description: "El observatorio natural tiene por objeto entender los procesos biogeoquímicos, hidrológicos y microbiológicos del ecosistema altoandino del sur del Ecuador.",
        date: "BIg. Jazmín Salazar MSc",
    },
    {
        Image: "/img/v-observatorio-educativo.png",
        id: 1,
        to: "/videos/n7",
        name: "Innovación Educativa",
        description: "La innovación es un recurso que se utiliza dentro de distintas áreas para renovar o impulsar las nuevas formas en que se pueden desarrollar los procesos con puntos de vistas más novedosos.",
        date: "Ing. Augusto Cabrera MSc",
    },
  ];
  