export const lista_proyectos = [
  {
    Image: "/img/Geoportal.png",
    id: 1,
    to: "/proyectos/canastabasica",
    name: "Canasta Básica",
    description: "Visualiza y compara datos sobre las canastas básicas en diferentes regiones del país en tiempo real.",
    date: "2023-08-01",
  },
  {
    Image: "/img/Geoportal.png",
    id: 2,
    to: "/proyectos/map",
    name: "Mapa Leaflet",
    description: "Visualiza y compara distintos datos con ayuda de un mapa en el pais de Ecuador",
    date: "2021-10-01",
  },
  {
    Image: "/img/Geoportal.png",
    id: 3,
    to: "/proyectos/map",
    name: "Proyecto 3",
    description: "Visualiza y compara distintos datos con ayuda de un mapa en el pais de Ecuador",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 4,
    to: "/proyectos/map",
    name: "Proyecto 4",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 5,
    to: "/proyectos/map",
    name: "Proyecto 5",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 6,
    to: "/proyectos/map",
    name: "Proyecto 6",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 7,
    to: "/proyectos/map",
    name: "Proyecto 7",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 8,
    to: "/proyectos/map",
    name: "Proyecto 8",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 9,
    to: "/proyectos/map",
    name: "Proyecto 9",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
  {
    Image: "/img/geovisor_mapa.png",
    id: 10,
    to: "/proyectos/map",
    name: "Proyecto 10",
    description: "Coloque la desripcion del proyecto numero 4",
    date: "2021-10-01",
  },
];
