export const lista_noticias = [
  {
    Image: "/img/C2MAD.jpg",
    id: 1,
    name: "La Red de Investigación y Observatorios de la Universidad Católica de Cuenca (RIOUC) despliega su propia plataforma web",
    date: "2024-07-01",
    author: "Ing. Alexánder Lozada",
    description: "En una innovadora movida tecnológica, la Red de Investigación y Observatorios de la Universidad Católica de Cuenca (RIOUC) ha lanzado su propia plataforma web, diseñada para ofrecer al mundo un acceso más profundo y detallado sobre sus actividades, investigaciones y el personal que la conforma. La nueva plataforma web de RIOUC es un recurso integral que abre sus puertas a múltiples secciones accesibles al público, proporcionando una ventana única hacia el conocimiento generado por la red. Entre las secciones disponibles, se destaca información detallada sobre su laboratorio en el CIITT, una presentación exhaustiva del personal, incluyendo doctores, ingenieros y técnicos, y una vista completa del equipo de los siete observatorios que conforman la red. En la sección de Boletines, los usuarios podrán acceder a las revistas publicadas por RIOUC, con la posibilidad de leer sinopsis detalladas y descargar los boletines originales. Esta herramienta es fundamental para investigadores y académicos que buscan mantenerse al día con los últimos hallazgos y estudios realizados por RIOUC. La sección de Proyectos destaca los geovisores desarrollados por RIOUC. Estos geovisores proporcionan información visual sobre diversos datos recolectados por los diferentes observatorios, permitiendo a los usuarios tanto visualizar como descargar estos valiosos datos. Es un recurso indispensable para aquellos interesados en la investigación y el análisis geoespacial. Tendencias Educativas es un espacio dedicado a las últimas novedades y noticias relacionadas con la Universidad Católica de Cuenca. Funciona como un pequeño blog informativo donde los usuarios pueden dejar sus comentarios y opiniones, fomentando un diálogo continuo entre la comunidad educativa y el público en general. La nueva plataforma web de RIOUC es una demostración del compromiso de la Universidad Católica de Cuenca con la transparencia y la accesibilidad del conocimiento, brindando herramientas que facilitan la difusión de sus investigaciones y el desarrollo de proyectos innovadores. Con esta iniciativa, RIOUC no solo fortalece su presencia digital, sino que también refuerza su papel como líder en investigación y educación en el ámbito científico y tecnológico.",
    },
  {
    Image: "/img/RV_augusto.png",
    id: 2,
    name: "Realidad Virtual: Democratizando el Conocimiento a Través de la Empatía",
    date: "2024-03-13",
    author: "Prof. Augusto Cabrera Duffaut",
    description: "La accesibilidad del conocimiento ha evolucionado enormemente, desde estar confinado en bibliotecas hasta la era digital que nos ofrece información ilimitada a través de Internet. Sin embargo, la verdadera comprensión del conocimiento requiere más que solo lectura; se necesita una interacción más profunda para asimilar conceptos complejos. La realidad virtual (RV) nos permite hacer justamente esto, ofreciendo experiencias inmersivas que se graban en nuestra memoria. Imaginemos sumergirnos en el cuerpo humano para observar el latido del corazón o trasladarnos a otra época para interactuar con figuras históricas. La RV no solo nos proporciona una visualización detallada, sino que también despierta conexiones emocionales, llevando a una comprensión más profunda y duradera. En el ámbito educativo, la RV se clasifica en experiencias no inmersivas, semi inmersivas e inmersivas, cada una ofreciendo distintos grados de interacción y realismo. Esta tecnología, ya utilizada en algunas aulas, permite a los estudiantes explorar órganos en detalle, facilitando una comprensión intuitiva de conceptos complejos. Mi investigación doctoral en la Universidad de Salamanca, España, se centra en la innovación tecnológica educativa. Junto con mis directoras, Ana Iglesias y Ana Llorente, hemos descubierto que el aprendizaje inmersivo aumenta significativamente la retención a largo plazo en comparación con métodos convencionales. Además, estamos desarrollando metodologías para implementar la RV en el aula, creando experiencias de aprendizaje vivenciales y memorables.",
  },
  ];
  
